#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# config/routes.yaml
app_category_generate_qr_codes:
    path: /category/generate-qr-codes
    controller: App\Controller\CategoryController::generateQrCodes

